# network architecture
# encoder related
etype: blstmp     # encoder architecture type
elayers: 4
eunits: 1024
eprojs: 1024
subsample: "1_2_2_1_1" # skip every n frame from input to nth layers
# decoder related
dlayers: 1
dunits: 1024
# attention related
atype: location
adim: 320
aconv-chans: 10
aconv-filts: 100

# hybrid CTC/attention
mtlalpha: 0.0

# minibatch related
batch-size: 18
maxlen-in: 700  # if input length  > maxlen_in, batchsize is automatically reduced
maxlen-out: 150 # if output length > maxlen_out, batchsize is automatically reduced

# other config
# not yet implemented
# dropout-rate: 0.2

# optimization related
sortagrad: 0 # Feed samples from shortest to longest ; -1: enabled for all epochs, 0: disabled, other: enabled for 'other' epochs
opt: adadelta
epochs: 25
patience: 0

# scheduled sampling option
sampling-probability: 0.5

# asrtts related options
criterion: acc
generator: tts
sample-topk: 0
sample-scaling: 0.1
teacher-weight: 0.1
n-samples: 5
