# network architecture
# encoder related
etype: vggblstm     # encoder architecture type
elayers: 4
eunits: 1024
eprojs: 1024
subsample: "1_2_2_1_1" # skip every n frame from input to nth layers
# decoder related
dlayers: 2
dunits: 1024
# attention related
atype: location
adim: 1024
aconv-chans: 10
aconv-filts: 100

# hybrid CTC/attention
mtlalpha: 0

# minibatch related
batch-size: 16
maxlen-in: 800  # if input length  > maxlen_in, batchsize is automatically reduced
maxlen-out: 150 # if output length > maxlen_out, batchsize is automatically reduced

# other config
dropout-rate: 0.2

# optimization related
sortagrad: 0 # Feed samples from shortest to longest ; -1: enabled for all epochs, 0: disabled, other: enabled for 'other' epochs
opt: adadelta
lr-factor: 0.031645
lr: 1e-3
warmup-steps: 1000
stop-steps: 20000       # stop keep original lr and strat decay
decay-rate: 0.49
decay-steps: 11000
final-lr: 1e-5
epochs: 45
patience: 0

# scheduled sampling option
sampling-probability: 0.0
